"""
Demo utilities: reset demo state, replay sample attack logs, fail2ban export.
"""
from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app import models
from app.database import SessionLocal
from app.simulator import ensure_log_file, seed_background_noise
from app.websocket import ws_manager

router = APIRouter(prefix="/api", tags=["demo"])

# backend/samples — two parents up from app/routers/demo.py is the backend root
SAMPLES_DIR = Path(__file__).resolve().parents[2] / "samples"

class ResetResponse(BaseModel):
    message: str


class ReplayRequest(BaseModel):
    sample: str = Field(..., description="Filename under samples/, e.g. ssh_bruteforce_cn.log")


class ReplayResponse(BaseModel):
    message: str
    lines_appended: int
    sample: str


class SampleInfo(BaseModel):
    name: str
    description: str
    size_bytes: int


@router.post("/demo/reset", response_model=ResetResponse)
async def reset_demo(request: Request):
    """
    Clear events, blocks, detection state, whitelist/blacklist, and the
    simulated log — then re-seed a few benign lines. Perfect for recruiter demos.
    """
    settings = request.app.state.settings
    detector = request.app.state.detector
    tailer = request.app.state.tailer

    db: Session = SessionLocal()
    try:
        db.query(models.Event).delete()
        db.query(models.BlockedIP).delete()
        db.query(models.WhitelistEntry).delete()
        db.query(models.BlacklistEntry).delete()
        db.query(models.DetectionState).delete()
        # Keep geo cache (useful) and tailer_state (we'll reset offset below)
        db.query(models.TailerState).delete()
        db.commit()
        detector.clear_all(db=db)
    finally:
        db.close()

    # Truncate simulated log and re-seed
    log_path = Path(settings.simulated_log_path)
    ensure_log_file(str(log_path))
    log_path.write_text("", encoding="utf-8")
    seed_background_noise(str(log_path), count=3)

    # Restart tailer from offset 0
    await tailer.stop()
    tailer.set_log_path(settings.log_path)
    await tailer.start()

    await ws_manager.broadcast({"type": "demo_reset"})
    return ResetResponse(message="Demo reset complete — feed cleared and log re-seeded")


@router.get("/samples", response_model=list[SampleInfo])
def list_samples():
    SAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    meta = {
        "ssh_bruteforce_cn.log": "Distributed SSH password spray from CN/HK-looking IPs",
        "ssh_bruteforce_ru.log": "High-intensity root brute force from a single RU IP",
        "ssh_mixed_noise.log": "Mixed legitimate traffic + slow credential stuffing",
    }
    out = []
    for path in sorted(SAMPLES_DIR.glob("*.log")):
        out.append(
            SampleInfo(
                name=path.name,
                description=meta.get(path.name, "Sample auth.log excerpt"),
                size_bytes=path.stat().st_size,
            )
        )
    return out


@router.post("/samples/replay", response_model=ReplayResponse)
async def replay_sample(body: ReplayRequest, request: Request):
    """
    Append a shipped sample attack log into the simulated auth log so the
    live tailer picks it up — demonstrates real-world-style threat data.
    """
    settings = request.app.state.settings
    if ".." in body.sample or "/" in body.sample or "\\" in body.sample:
        raise HTTPException(status_code=400, detail="Invalid sample name")

    src = SAMPLES_DIR / body.sample
    if not src.exists() or not src.is_file():
        raise HTTPException(status_code=404, detail=f"Sample not found: {body.sample}")

    ensure_log_file(settings.simulated_log_path)
    content = src.read_text(encoding="utf-8")
    lines = [ln for ln in content.splitlines() if ln.strip()]
    with open(settings.simulated_log_path, "a", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
        f.flush()

    return ReplayResponse(
        message=f"Replaying {body.sample} ({len(lines)} lines)",
        lines_appended=len(lines),
        sample=body.sample,
    )


@router.get("/export/fail2ban", response_class=PlainTextResponse)
def export_fail2ban(request: Request):
    """
    Generate a fail2ban-style filter + jail snippet from current thresholds.
    Copy into /etc/fail2ban/ on a real server to bridge this tool with industry tooling.
    """
    s = request.app.state.settings
    findtime = s.time_window_minutes * 60
    maxretry = s.block_threshold
    bantime = s.unblock_after_hours * 3600

    content = f"""# Generated by SSH Brute Force Detector
# Save filter as: /etc/fail2ban/filter.d/sshd-detector.conf
# Save jail as:   /etc/fail2ban/jail.d/sshd-detector.conf
# Then:           sudo fail2ban-client reload

# --- filter.d/sshd-detector.conf ---
[Definition]
failregex = ^%(__prefix_line)s(?:error: )?PAM: Authentication failure for .* from <HOST>\\s*$
            ^%(__prefix_line)sFailed password for .* from <HOST>(?: port \\d*)?(?: ssh\\d*)?$
            ^%(__prefix_line)sInvalid user .* from <HOST>(?: port \\d*)?\\s*$
ignoreregex =

# --- jail.d/sshd-detector.conf ---
[sshd-detector]
enabled  = true
port     = ssh
filter   = sshd-detector
logpath  = %(sshd_log)s
backend  = %(sshd_backend)s
maxretry = {maxretry}
findtime = {findtime}
bantime  = {bantime}
# Generated from detector thresholds:
#   alert={s.alert_threshold}  rate_limit={s.rate_limit_threshold}  block={s.block_threshold}
#   window={s.time_window_minutes}m  unblock_after={s.unblock_after_hours}h
"""
    return PlainTextResponse(content, media_type="text/plain")
